name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: feff-rs
            asset_name: feff-rs-linux-amd64
          - os: windows-latest
            artifact_name: feff-rs.exe
            asset_name: feff-rs-windows-amd64.exe
          - os: macos-latest
            artifact_name: feff-rs
            asset_name: feff-rs-macos-amd64

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      # Build with optimizations
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      
      # Prepare the artifact
      - name: Prepare artifact
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            cp target/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}
          else
            cp target/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}
          fi
        shell: bash
      
      # Upload binaries to release
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}